---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  API_KEY: create_google_apikey

test:
  DB_FILENAME: db/local/test.db
  API_KEY:  create_google_apikey

production:
  API_KEY:  create_google_apikey